# -*- coding: utf-8 -*-
"""Actividad1_Ejercicio5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLgiAnrVCLOxwYnnj7BALGKwd6Scy0RF
"""

import math

class geometria:
    @staticmethod
    def area_circulo(radio):
        return math.pi * (pow(radio, 2))

    @staticmethod
    def longuitud_circulo(radio):
        return 2 * math.pi * radio


radio = float(input("Ingrese el radio del círculo: "))

print(f"El área del círculo es: {round(geometria.area_circulo(radio), 2)}")
print(f"La longitud del círculo es: {round(geometria.longuitud_circulo(radio), 2)}")