# -*- coding: utf-8 -*-
"""Actividad1_Ejercicio3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DgYvk1SdI5lIxPw2sBCgTCECP0ACF_dL
"""

class op_nomina:
    @staticmethod
    def salario_bruto(horas_trabajadas, valor_hora):
        return horas_trabajadas * valor_hora

    @staticmethod
    def valor_retefuente(por_retefuente, salario_bruto):
        return por_retefuente * salario_bruto

    @staticmethod
    def salario_neto(salario_bruto, valor_retefuente):
        return salario_bruto - valor_retefuente


horas_trabajadas = 48.0
valor_hora = 5000.0
retencion = 12.5
por_retefuente = retencion / 100

salario_bruto = op_nomina.salario_bruto(horas_trabajadas, valor_hora)
valor_retefuente = op_nomina.valor_retefuente(por_retefuente, salario_bruto)
salario_neto = op_nomina.salario_neto(salario_bruto, valor_retefuente)

print(f"El salario bruto es de: {salario_bruto}")
print(f"La retención en la Fuente es de: {valor_retefuente}")
print(f"El salario neto es de: {salario_neto}")