# -*- coding: utf-8 -*-
"""Actividad1_Ejercicio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeJ0yltXs5RkeMaMjq21tvxKdRzTPaSM
"""

class operaciones:
    @staticmethod
    def cuadrado(x):
        return x**2

    @staticmethod
    def cubo(x):
        return x**3


x = float(input("Ingrese el número que desea modificar: "))

print(f"El número era: {x}")
print(f"El cuadrado del número es: {operaciones.cuadrado(x)}")
print(f"El cubo del número es: {operaciones.cubo(x)}")