# -*- coding: utf-8 -*-
"""Actividad1_Ejercicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eif4U9N4-v3dVBEG6250b1mSDqRcPwCR
"""

class Age:
    @staticmethod
    def edadalber(Juan):
        return (2 * Juan) / 3

    @staticmethod
    def edadana(Juan):
        return (4 * Juan) / 3

    @staticmethod
    def edadmom(edadana, edadalber, Juan):
        return edadana + edadalber + Juan


Juan = int(input("Ingrese la edad de Juan: "))

print(f"La edad de Juan es: {Juan}")

alber = Age.edadalber(Juan)
print(f"La edad de Alberto es: {alber}")

ana = Age.edadana(Juan)
print(f"La edad de Ana es: {ana}")

mama = Age.edadmom(ana, alber, Juan)
print(f"La edad de la mamá es: {mama}")