# -*- coding: utf-8 -*-
"""Actividad1_Ejercicio2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1P3ho2EZtycohM3conYigA9rxHk_B24
"""

class Operaciones:
  @staticmethod
  def ope(x,y):
    return x + y**2

suma = 0
x = 20
y = 40
suma += x
x = Operaciones.ope(x,y)
suma += (x/y)

print(f"El valor de x es: {x}")
print(f"El valor de y es: {y}")
print(f"La suma es: {suma}")